openapi: 3.0.1
info:
  title: CovidStatusAPI
  description: API Definition of CovidStatusAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/covid
paths:
  /status:
    get:
      responses:
        default:
          description: Default response
  /status/{country}:
    get:
      parameters:
      - name: country
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
