openapi: 3.0.1
info:
  title: helloAPI
  description: API Definition of helloAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/hello
paths:
  /:
    get:
      responses:
        default:
          description: Default response
